# docker-compose.yml
version: "3.3"
services:
  postgres:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    image: postgres:15
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - /root/database:/var/lib/postgresql/admin_postgres
