name:                gpt-discord-chatbot
version:             0.1.0.0
github:              "mtamc/gpt-discord-chatbot"
license:             BSD3
author:              "mtamc"
maintainer:          "mtamc"
copyright:           "2022 mtamc"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/mtamc/gpt-discord-chatbot#readme>

dependencies:
- base-noprelude
- relude
- discord-haskell
- unliftio
- http-types
- http-conduit
- text
- aeson
- lens
- generic-lens
- mtl
- template-haskell
- data-default
- base-unicode-symbols
- safe-exceptions
- opaleye
- product-profunctors
- postgresql-simple
- dhall
- time
- http-client

language: GHC2021

default-extensions:
- OverloadedStrings
- OverloadedLabels
- UnicodeSyntax
- NoFieldSelectors
- LambdaCase
- DuplicateRecordFields
- ViewPatterns
- BlockArguments
- DataKinds
- TypeOperators
- TypeFamilies
- OverloadedRecordDot

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

library:
  source-dirs: src

executables:
  gpt-discord-chatbot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=.hie
    dependencies:
    - gpt-discord-chatbot

tests:
  gpt-discord-chatbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gpt-discord-chatbox
